# Random Forest model

In [129]:
# Import our dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
import matplotlib.pyplot as plt

# Import depenencies for confusionmatrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# import tensorflow as tf
from sqlalchemy import create_engine
from config import db_password


In [130]:
# sklearn dependancies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

### Connecting to postgreSQL Database "wnba_champs"

In [131]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/wnba_champs"
engine = create_engine(db_string)

### Pulling data from database

In [132]:
# Extracting "stats" data from postgreSQL wnba_champs database.
stats_df = pd.read_sql("select * from \"stats\"", db_string);
stats_df.head()

index  Position   Season   Tm   Age   W   L  Win_pct  PW  PL  ...   3PAr  \
0      0         1  1997-98  HOC  28.8  18  10   0.6429  22   6  ...  0.292   
1      1         0  1997-98  PHM  27.9  16  12   0.5714  20   8  ...  0.247   
2      2         0  1997-98  NYL  27.5  17  11   0.6071  17  11  ...  0.198   
3      3         0  1997-98  LAS  25.5  14  14   0.5000  17  11  ...  0.136   
4      4         0  1997-98  CLR  28.1  15  13   0.5357  16  12  ...  0.108   

   TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0   0.523    0.473     20.4     36.2   0.266        0.444         22.3   
1   0.473    0.411     18.8     33.2   0.274        0.441         24.2   
2   0.482    0.439     21.3     34.6   0.236        0.422         22.7   
3   0.504    0.464     20.4     32.7   0.235        0.423         19.4   
4   0.515    0.464     21.6     32.2   0.276        0.449         20.2   

   opp_DRB%  Opp_FT_FGA  
0      64.7       0.236  
1      68.5       0.245  
2      64.7       0.246  
3      67.9       0.263  
4      67.1       0.219  

[5 rows x 28 columns]

In [133]:
# Extracting cy_stats data from PostgreSQL wnba_champs database.
test_df= pd.read_sql("select * from \"cy_stats\"", db_string)
test_df

index  Position   Season   Tm   Age   W   L  Win_pct  PW  PL  ...   3PAr  \
0       0         0  2021-22  COS  28.3  26   6   0.8125  28   4  ...  0.298   
1       1         1  2021-22  LVA  26.4  24   8   0.7500  26   6  ...  0.192   
2       2         0  2021-22  SES  28.1  21  11   0.6563  22  10  ...  0.328   
3       3         0  2021-22  MLY  27.6  22  10   0.6875  21  11  ...  0.296   
4       4         0  2021-22  PHM  28.4  19  13   0.5938  19  13  ...  0.332   
5       5         0  2021-22  CSK  28.4  16  16   0.5000  18  14  ...  0.304   
6       6         0  2021-22  DAW  24.8  14  18   0.4375  15  17  ...  0.327   
7       7         0  2021-22  WAM  28.7  12  20   0.3750  11  21  ...  0.396   
8       8         0  2021-22  LAS  27.5  12  20   0.3750  10  22  ...  0.306   
9       9         0  2021-22  ATD  27.4   8  24   0.2500   9  23  ...  0.269   
10     10         0  2021-22  NYL  25.7  12  20   0.3750   7  25  ...  0.420   
11     11         0  2021-22  INF  27.3   6  26   0.1875   5  27  ...  0.253   

    TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0    0.543    0.497     15.9     31.2   0.220        0.459         16.1   
1    0.559    0.508     12.6     21.3   0.255        0.464         12.5   
2    0.556    0.512     13.9     20.9   0.206        0.483         14.4   
3    0.553    0.508     15.8     22.3   0.218        0.476         14.6   
4    0.553    0.507     14.7     23.8   0.235        0.466         11.3   
5    0.538    0.493     15.1     23.8   0.205        0.480         15.9   
6    0.521    0.477     14.1     27.8   0.193        0.505         14.1   
7    0.519    0.475     13.7     21.9   0.203        0.520         15.3   
8    0.501    0.462     15.4     17.4   0.181        0.476         19.2   
9    0.489    0.459     12.1     24.6   0.154        0.520         16.8   
10   0.541    0.504     18.2     18.4   0.181        0.488         13.2   
11   0.498    0.453     15.4     27.4   0.199        0.517         13.6   

    opp_DRB%  Opp_FT_FGA  
0       82.1       0.201  
1       80.0       0.165  
2       78.6       0.180  
3       79.7       0.194  
4       75.1       0.167  
5       73.9       0.212  
6       77.6       0.206  
7       76.4       0.208  
8       71.4       0.267  
9       73.7       0.234  
10      75.2       0.203  
11      75.6       0.222  

[12 rows x 28 columns]

In [134]:
# Extracting Season, TM and Team_Name into DF
name_df = stats_df[['Season', 'Tm']]
name_df.head()

Season   Tm
0  1997-98  HOC
1  1997-98  PHM
2  1997-98  NYL
3  1997-98  LAS
4  1997-98  CLR

In [135]:
# Drop LG, Season, TM, Team_Name, W, L columns
stats_df.drop(['index', 'Age', 'Season','Tm', 'W', 'L'], axis=1, inplace=True)
stats_df.head()

Position  Win_pct  PW  PL   MOV   SOS   SRS  ORtg  DRtg  NRtg  ...   3PAr  \
0         1   0.6429  22   6  6.32 -0.79  5.53  99.4  90.7   8.7  ...  0.292   
1         0   0.5714  20   8  4.00 -0.48  3.38  91.4  86.1   5.3  ...  0.247   
2         0   0.6071  17  11  2.39 -0.32  2.22  90.6  87.4   3.2  ...  0.198   
3         0   0.5000  17  11  2.21 -0.23  1.63  93.9  91.1   2.8  ...  0.136   
4         0   0.5357  16  12  1.79 -0.22  1.56  94.4  92.0   2.4  ...  0.108   

   TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0   0.523    0.473     20.4     36.2   0.266        0.444         22.3   
1   0.473    0.411     18.8     33.2   0.274        0.441         24.2   
2   0.482    0.439     21.3     34.6   0.236        0.422         22.7   
3   0.504    0.464     20.4     32.7   0.235        0.423         19.4   
4   0.515    0.464     21.6     32.2   0.276        0.449         20.2   

   opp_DRB%  Opp_FT_FGA  
0      64.7       0.236  
1      68.5       0.245  
2      64.7       0.246  
3      67.9       0.263  
4      67.1       0.219  

[5 rows x 22 columns]

In [136]:
# exploring data
stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Position     316 non-null    int64  
 1   Win_pct      316 non-null    float64
 2   PW           316 non-null    int64  
 3   PL           316 non-null    int64  
 4   MOV          316 non-null    float64
 5   SOS          316 non-null    float64
 6   SRS          316 non-null    float64
 7   ORtg         316 non-null    float64
 8   DRtg         316 non-null    float64
 9   NRtg         316 non-null    float64
 10  Pace         316 non-null    float64
 11  FTr          316 non-null    float64
 12  3PAr         316 non-null    float64
 13  TS_pct       316 non-null    float64
 14  eFG_pct      316 non-null    float64
 15  TOV_pct      316 non-null    float64
 16  ORB_pct      316 non-null    float64
 17  FT_FGA       316 non-null    float64
 18  Opp_eFG_pct  316 non-null    float64
 19  Opp_TOV_

In [137]:
# exploring data
stats_df.shape

(316, 22)

In [138]:
# Drop Position target from features data
y = stats_df.Position
X = stats_df.drop(columns=["Position"])

In [139]:
# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [140]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Scale the data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [141]:
# Create a random forest classifier.
rf_model = RandomForestClassifier()

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest accuracy score: {accuracy_score(y_test,y_pred):.3f}")

 Random forest accuracy score: 0.899


In [142]:
# create a confusion metrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[71  2]
 [ 6  0]]


In [143]:
# confusion matrix using confusion matrx display
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=rf_model.classes_)
disp.plot()

# save image as png
plt.savefig("./Images/RandomForestClassifier_matrix.png")
plt.show()

### Since WNBA season has not started this year, we used the last year stats as current year (cy). 
### In order to make (cy) new and unknown, we created a dummy year using a combination of rando years for the teams to test the model.

In [144]:
# Extract Season, TM and Team_Name into DF
test_name_df = test_df[['Season', 'Tm']]
test_name_df

Season   Tm
0   2021-22  COS
1   2021-22  LVA
2   2021-22  SES
3   2021-22  MLY
4   2021-22  PHM
5   2021-22  CSK
6   2021-22  DAW
7   2021-22  WAM
8   2021-22  LAS
9   2021-22  ATD
10  2021-22  NYL
11  2021-22  INF

In [145]:
test_df_pos= test_df['Position']
test_df.drop(['index', 'Age', 'Position','Season','Tm', 'W', 'L',], axis=1, inplace=True)
test_df

Win_pct  PW  PL   MOV   SOS   SRS   ORtg   DRtg  NRtg  Pace  ...   3PAr  \
0    0.8125  28   4  9.81 -0.95  8.86  106.9   93.7  13.2  74.0  ...  0.298   
1    0.7500  26   6  9.06 -0.62  8.44  109.1   98.0  11.1  80.8  ...  0.192   
2    0.6563  22  10  4.44 -0.63  3.80  106.3  100.7   5.6  78.2  ...  0.328   
3    0.6875  21  11  4.00 -0.37  3.63  104.2   99.1   5.1  78.7  ...  0.296   
4    0.5938  19  13  2.56 -0.12  2.45  106.5  103.2   3.3  76.4  ...  0.332   
5    0.5000  18  14  1.31 -0.22  1.10  102.9  101.3   1.6  79.6  ...  0.304   
6    0.4375  15  17 -0.53  0.30 -0.23  104.3  105.0  -0.7  77.2  ...  0.327   
7    0.3750  11  21 -3.84  0.26 -3.58  101.5  106.4  -4.9  78.3  ...  0.396   
8    0.3750  10  22 -4.34  0.55 -3.79   93.7   99.3  -5.6  77.1  ...  0.306   
9    0.2500   9  23 -5.63  0.24 -5.38   99.3  106.4  -7.1  78.6  ...  0.269   
10   0.3750   7  25 -7.03  0.71 -6.32   97.0  105.7  -8.7  80.6  ...  0.420   
11   0.1875   5  27 -9.81  0.85 -8.97   97.4  110.1 -12.7  77.3  ...  0.253   

    TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0    0.543    0.497     15.9     31.2   0.220        0.459         16.1   
1    0.559    0.508     12.6     21.3   0.255        0.464         12.5   
2    0.556    0.512     13.9     20.9   0.206        0.483         14.4   
3    0.553    0.508     15.8     22.3   0.218        0.476         14.6   
4    0.553    0.507     14.7     23.8   0.235        0.466         11.3   
5    0.538    0.493     15.1     23.8   0.205        0.480         15.9   
6    0.521    0.477     14.1     27.8   0.193        0.505         14.1   
7    0.519    0.475     13.7     21.9   0.203        0.520         15.3   
8    0.501    0.462     15.4     17.4   0.181        0.476         19.2   
9    0.489    0.459     12.1     24.6   0.154        0.520         16.8   
10   0.541    0.504     18.2     18.4   0.181        0.488         13.2   
11   0.498    0.453     15.4     27.4   0.199        0.517         13.6   

    opp_DRB%  Opp_FT_FGA  
0       82.1       0.201  
1       80.0       0.165  
2       78.6       0.180  
3       79.7       0.194  
4       75.1       0.167  
5       73.9       0.212  
6       77.6       0.206  
7       76.4       0.208  
8       71.4       0.267  
9       73.7       0.234  
10      75.2       0.203  
11      75.6       0.222  

[12 rows x 21 columns]

In [146]:
# fit and trandform our X_encoded
df_X_test_scaled = scaler.fit_transform(test_df)

In [147]:
# view of the first row
df_X_test_scaled[:1]

array([[ 1.63290316,  1.66644651, -1.66644651,  1.63213306, -1.72779638,
         1.61489198,  0.9913437 , -1.99246513,  1.7120771 , -2.26783037,
         0.63687529, -0.20971216,  0.5126428 ,  0.43927693,  0.74269984,
         2.05381718,  0.62409574, -1.35226424,  0.67006252,  1.86176764,
        -0.14428111]])

In [148]:
df_test_df=rf_model.predict(df_X_test_scaled)
df_test_df

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [149]:
rf_model.predict_proba(df_X_test_scaled)

array([[0.28, 0.72],
       [0.56, 0.44],
       [0.94, 0.06],
       [0.99, 0.01],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.94, 0.06],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.99, 0.01],
       [1.  , 0.  ]])

In [150]:
cy_test_df = pd.DataFrame(df_test_df, columns = ['Position'])
cy_test_df.head()

Position
0         1
1         0
2         0
3         0
4         0

In [151]:
joined_df = test_name_df.join(cy_test_df)
joined_df

Season   Tm  Position
0   2021-22  COS         1
1   2021-22  LVA         0
2   2021-22  SES         0
3   2021-22  MLY         0
4   2021-22  PHM         0
5   2021-22  CSK         0
6   2021-22  DAW         0
7   2021-22  WAM         0
8   2021-22  LAS         0
9   2021-22  ATD         0
10  2021-22  NYL         0
11  2021-22  INF         0

### The most probable winner = Connecticut Sun - 72.0%

### Actual results: Since wnba season has ended we know the actual winner. The LAV won the 2022 WNBA championship.

### The model did a good job predicting the most likely winners for the season since LAV came in 2nd place with 32.0%

### This reflect that there are other factors that can influence the outcome of a season, like team cohesion, experience, coaching, ect.

## Test 2

### Since wnba season has not started, test 2 as performed using a dummy dataset create with real wnba historical data.
### The intention is to evaluate if the model can predict a winner.

In [153]:
# Extracting cy_stats2 data from PostgreSQL wnba_champs database.
test2_df= pd.read_sql("select * from \"cy_stats2\"", db_string)
test2_df.head(10)

index  Position   Season   Tm   Age   W   L  Win_pct  PW  PL  ...   3PAr  \
0      0         1  2016-17  MLY  30.6  28   6   0.8235  28   6  ...  0.175   
1      1         0  2016-17  LAS  28.7  26   8   0.7647  26   8  ...  0.245   
2      2         1  2017-18  SES  27.6  15  19   0.4412  17  17  ...  0.314   
3      3         0  2017-18  DAW  24.8  16  18   0.4706  13  21  ...  0.295   
4      4         1  2018-19  WAM  27.9  22  12   0.6471  21  13  ...  0.344   
5      5         0  2018-19  ATD  27.4  23  11   0.6765  20  14  ...  0.263   
6      6         0  2019-20  INF  26.0  13  21   0.3824  13  21  ...  0.244   
7      7         0  2019-20  NYL  26.5  10  24   0.2941   7  27  ...  0.282   
8      8         1  2020-21  CSK  27.2  12  10   0.5455  13   9  ...  0.317   
9      9         0  2020-21  PHM  28.0  13   9   0.5909  13   9  ...  0.366   

   TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0   0.551    0.500     14.8     30.2   0.254        0.458         16.7   
1   0.574    0.533     15.9     22.3   0.229        0.471         16.1   
2   0.574    0.530     16.5     20.8   0.236        0.491         14.8   
3   0.521    0.453     14.3     29.9   0.308        0.521         16.0   
4   0.558    0.510     13.0     25.5   0.223        0.496         14.9   
5   0.514    0.468     13.5     26.8   0.231        0.468         15.2   
6   0.508    0.464     14.4     26.5   0.202        0.473         13.7   
7   0.504    0.461     16.0     25.6   0.193        0.491         13.8   
8   0.580    0.547     16.6     23.3   0.178        0.503         15.0   
9   0.564    0.513     15.5     22.2   0.259        0.477         14.2   

   opp_DRB%  Opp_FT_FGA  
0      75.6       0.233  
1      73.2       0.201  
2      71.1       0.207  
3      72.7       0.261  
4      72.7       0.223  
5      72.7       0.203  
6      72.7       0.205  
7      73.2       0.242  
8      76.4       0.205  
9      73.1       0.233  

[10 rows x 28 columns]

In [154]:
# Extract Season, TM and Team_Name into DF
test2_name_df = test2_df[['Season', 'Tm']]
test2_name_df.head()

Season   Tm
0  2016-17  MLY
1  2016-17  LAS
2  2017-18  SES
3  2017-18  DAW
4  2018-19  WAM

In [155]:
# Drop LG, Season, TM, Team_Name, G, W, L columns
test2_df.drop(['index', 'Age', 'Position', 'Season','Tm', 'W', 'L'], axis=1, inplace=True)
test2_df.head()

Win_pct  PW  PL   MOV   SOS   SRS   ORtg   DRtg  NRtg  Pace  ...   3PAr  \
0   0.8235  28   6  8.82 -0.70  8.13  108.2   97.1  11.1  78.2  ...  0.175   
1   0.7647  26   8  7.09 -0.77  6.31  107.8   98.6   9.2  76.4  ...  0.245   
2   0.4412  17  17  0.00 -0.17 -0.17  105.8  105.8   0.0  77.2  ...  0.314   
3   0.4706  13  21 -2.65  0.42 -2.23  105.4  108.7  -3.3  80.5  ...  0.295   
4   0.6471  21  13  3.06 -0.10  2.99  110.7  106.6   4.1  76.3  ...  0.344   

   TS_pct  eFG_pct  TOV_pct  ORB_pct  FT_FGA  Opp_eFG_pct  Opp_TOV_pct  \
0   0.551    0.500     14.8     30.2   0.254        0.458         16.7   
1   0.574    0.533     15.9     22.3   0.229        0.471         16.1   
2   0.574    0.530     16.5     20.8   0.236        0.491         14.8   
3   0.521    0.453     14.3     29.9   0.308        0.521         16.0   
4   0.558    0.510     13.0     25.5   0.223        0.496         14.9   

   opp_DRB%  Opp_FT_FGA  
0      75.6       0.233  
1      73.2       0.201  
2      71.1       0.207  
3      72.7       0.261  
4      72.7       0.223  

[5 rows x 21 columns]

In [156]:
df_X_test2_scaled = scaler.fit_transform(test2_df)

In [157]:
df_test2_df=rf_model.predict(df_X_test2_scaled)
df_test2_df

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
rf_model.predict_proba(df_X_test2_scaled)

array([[0.54, 0.46],
       [0.95, 0.05],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.92, 0.08],
       [0.98, 0.02],
       [0.63, 0.37],
       [0.52, 0.48]])

In [159]:
cy_test2_df = pd.DataFrame(df_test2_df, columns = ['Position'])
cy_test2_df.head()

Position
0         0
1         0
2         0
3         0
4         0

In [160]:
joined2_df = test2_name_df.join(cy_test2_df)
joined2_df

Season   Tm  Position
0   2016-17  MLY         0
1   2016-17  LAS         0
2   2017-18  SES         0
3   2017-18  DAW         0
4   2018-19  WAM         0
5   2018-19  ATD         0
6   2019-20  INF         0
7   2019-20  NYL         0
8   2020-21  CSK         0
9   2020-21  PHM         0
10  2021-22  LVA         0
11  2021-22  COS         0

### The most probable winner = Minnesota Lynx 46.0%

### Per our model the most likely winner for our random dataset is MLY. This correlates to the data since MLY had the best stats among the teams.

### The MLY actually won the WNBA Championship for 2017 season. 